[workspace]

members = [
    "accounts",
    "accounts-proto",
    "common",
    "fraud-detector",
    "ledger",
    "ledger-consumer",
    "ledger-proto",
    "pasys",
    "pasys-api",
    "refund-processor",
    "settlement-processor",
    ]
