[package]
name = "ledger-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.14.1"
tonic-reflection = "0.14.1"
prost = "0.14.1"
prost-types = "0.14.1"
tonic-prost = "0.14.1"

[build-dependencies]
tonic-build = "0.14.1"
tonic-prost-build = "0.14.1"